# To run from a remote Docker container definition:
# docker compose up -d
# docker compose exec jekyll foreman start

# This was useful for Docker:
# https://dev.to/michael/compile-a-jekyll-project-without-installing-jekyll-or-ruby-by-using-docker-4184

# This was useful for Bootstrap (although I still have to figure out stuff for myself):
# https://simpleit.rocks/ruby/jekyll/tutorials/how-to-add-bootstrap-4-to-jekyll-the-right-way/

title: Verapax
email: verapax@gmail.com
twitter_username: _amcontreras
github_username:  lcreid

url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/next" # the subpath of your site, e.g. /blog

sass:
  load_paths:
    - _sass
    - node_modules
  silence_deprecations:
    - color-functions
    - global-builtin
    - import

exclude:
  - .devcontainer/
  - .devcontainer.json
  - .vscode/
  - .vscode-server/
  - compose.yml
  - LICENSE
  - Makefile
  - node_modules/
  - package-lock.json
  - package.json
  - Procfile*
  - README.md
  - Vagrantfile
  - yarn.lock

include:
  - node_modules/@popperjs/core/dist/umd/popper.min.js
  - node_modules/@popperjs/core/dist/umd/popper.min.js.map
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js.map
