# To run from a remote Docker container definition:
# export JEKYLL_VERSION=3.8.5
# docker run -p 4000:4000 --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -it jekyll/jekyll:$JEKYLL_VERSION jekyll serve

# This was useful for Docker:
# https://dev.to/michael/compile-a-jekyll-project-without-installing-jekyll-or-ruby-by-using-docker-4184

# This was useful for Bootstrap (although I still have to figure out stuff for myself):
# https://simpleit.rocks/ruby/jekyll/tutorials/how-to-add-bootstrap-4-to-jekyll-the-right-way/

title: Verapax
email: verapax@gmail.com
twitter_username: _amcontreras
github_username:  lcreid

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/next" # the subpath of your site, e.g. /blog

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - Vagrantfile
  - yarn.lock

include:
  - node_modules/jquery/dist/jquery.min.js
  - node_modules/popper.js/dist/umd/popper.min.js
  - node_modules/popper.js/dist/umd/popper.min.js.map
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js.map